# 自定义的Swagger属性配置
customize:
  swagger:
    enable: false
    is-production: false
    title: 接口文档管理中心
    description: 接口文档管理中心
    license: Powered by olinonee
    license-url: https://gitee.com/olinonee
    terms-of-service-url: https://gitee.com/olinonee
    contact-name: olinonee
    contact-url: https://gitee.com/olinonee
    contact-email: olinone666@gmail.com

# knife4j配置
knife4j:
  enable: ${customize.swagger.enable}
  # 开启生产环境屏蔽
  production: ${customize.swagger.is-production}
  basic:
    enable: true
    username: root
    password: root
  setting:
    # 是否不显示Knife4j默认的footer，默认为true(显示)
    enableFooter: false
    # 是否自定义Footer，默认为false(非自定义)
    enableFooterCustom: true
    # 自定义Footer内容,支持Markdown语法
    footerCustomContent: Apache License 2.0 | Copyright  2020-[olinonee](https://gitee.com/olinonee)
    #enableHomeCustom: true
    #homeCustomLocation: classpath:mate-swagger.md
  documents: # 文档配置，可配置多个分组
    - group: restApi
      name: 接口说明文档
      locations: classpath:markdown/*

# 默认路径匹配策略切换回ant_path_matcher
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
